object Versions {
    const val buildGradleVersion = "4.0.0"
    const val googleServicesVersion = "4.3.3"
    const val navigationSafeArgsVersion = "2.3.0-alpha06"

    const val kotlinVersion = "1.3.72"
    const val appcompatVersion = "1.1.0"
    const val coreKTXVersion = "1.2.0"
    const val constraintLayoutVersion = "1.1.3"

    const val navigationFragmentKTXVersion = "2.3.0-alpha06"
    const val lifecycleExtensionsVersion = "2.2.0"
    const val lifecycleViewModelKTXVersion = "2.2.0"
    const val lifecycleLiveDataKTXVersion = "2.2.0"
    const val picassoVersion = "2.71828"
    const val retrofitVersion = "2.7.1"
    const val okHttpVersion = "4.3.1"
    const val daggerVersion = "2.27"
    const val daggerAndroidVersion = "2.27"
    const val viewpager2Version = "1.0.0"
    const val sweetAlertLibraryVersion = "1.6.2"
    const val leakCanaryAndroidVersion = "2.2"
    const val materialVersion = "1.2.0-alpha05"
    const val cameraVersion = "1.0.0-beta01"
    const val cameraViewVersion = "1.0.0-alpha08"
    const val cameraEXTVersion = "1.0.0-alpha08"
    const val roomVersion = "2.2.5"
    const val swipeRefreshLayoutVersion = "1.0.0"
}